### ISSUE TITLE
optionally show entry in a popup window for small &cmdheight

### ISSUE THREAD

**Issue by Konfekt** [inkarkat/vim-QuickFixCurrentNumber#2]
If `&cmdheight` is too small to display the quickfix entry, a key must be pressed after `:Cnr` to continue.
How about optionally using (an adaption of `:CpDialogCommand Cnr`) https://github.com/kennypete/vim-popped to show it in a popup instead?

**Comment by inkarkat** [comment]
If I understand this correctly, `:CpDialogCommand Cnr` already works out of the box. As that's tedious to type, I'd use something like the [cmdalias plugin](http://www.vim.org/scripts/script.php?script_id=746) to define a shorter alias for it (e.g. `:CpDCnr`).

If vim-popped supported a pass-through option that simplied echoes the captured output if it fits, and only uses a popup window if it doesn't, one could actually transparently override the plugin's `:Cnr` command with it. There are several more Vim commands (both built-in and provided by plugins) where this could be beneficial (if one is allergic to scrolling and instead likes popup windows, that is). vim-popped looks very interesting!

On the other hand, adding a configuration option and optional dependency to vim-QuickFixCurrentNumber doesn't feel right. Someone else might prefer to have `'cmdheight'` temporarily increased, or use the preview window instead, and all of these variations would then need to be supported by the plugin as well. I don't think I would want to do this...
